CodeZoneTest/ViewModels/Shared/ErrorViewModel.cs
namespace CodeZoneTest.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

CodeZoneTest/ViewModels/Shared/PaginationViewModel.cs
namespace CodeZoneTest.Models;

public class PaginationViewModel<T>
{
    public int TotalItems  { get; set; }
    public int PageIndex { get; set; }
    public int PageSize { get; set; }
    public IEnumerable<T> Items { get; set; } = new List<T>();
    public int TotalPages  { get; set; }
}

CodeZoneTest/Controllers/ItemController.cs
using CodeZoneTest.Data.Models;
using CodeZoneTest.Interfaces;
using CodeZoneTest.Models.ItemViewModels;
using CodeZoneTest.Services;
using CodeZoneTest.ViewModels.ItemViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CodeZoneTest.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemServices _itemService;
        private readonly IStoreItemsServices _storeItemsServices;

        public ItemController(IItemServices itemService , IStoreItemsServices storeItemsServices)
        {
            _itemService = itemService;
            _storeItemsServices = storeItemsServices;
        }
        public async Task<IActionResult> Index(int pageIndex, int pageSize)
        {
            var Items = await _itemService .Items(pageIndex, pageSize);
            var model = new IndexItemViewModel
            {
                AllItemsModel = Items,
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return PartialView("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddItemViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            await _itemService.AddItem(viewModel);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            var Item = _storeItemsServices.GetItemWithStores(id);
            return View(Item);
        }

        [HttpPost]
        public IActionResult Update(GetItemViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
             _itemService.UpdateItem(viewModel);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(string Id)
        {
            var oldItem = await _itemService.GetItemById(Id);
            return PartialView(oldItem);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var Item = await _itemService.GetItemById(id);
            return PartialView(Item);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id, bool confirmDelete = true)
        {
            var Item = await _itemService.DeleteItem(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

CodeZoneTest/Controllers/StoreController.cs
using CodeZoneTest.Interfaces;
using CodeZoneTest.Models.StoreViewModels;
using CodeZoneTest.ViewModels.StoreViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace CodeZoneTest.Controllers;

public class StoreController : Controller
{
    private readonly IStoreServices _storeService;
    private readonly IStoreItemsServices _storeItemsServices;

    public StoreController(IStoreServices storeService ,IStoreItemsServices storeItemsServices)
    {
        _storeService = storeService;
        _storeItemsServices = storeItemsServices;
    }
    public async Task<IActionResult> Index(int pageIndex , int pageSize)
    {
        var stores =await _storeService.Stores(pageIndex , pageSize);
        var model = new IndexStoreViewModel
        {
            AllStoresModel = stores,
        };
        return View(model);
    }
    [HttpGet]
    public IActionResult Create()
    {
        return PartialView("Create");
    }

    [HttpPost]
    public async Task<IActionResult> Create(AddStoreViewModel viewModel)
    {
        if(!ModelState.IsValid)
        {
            return View(viewModel);
        }
        await _storeService.AddStore(viewModel);
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Details(string id)
    {
        var Item = _storeItemsServices.GetStoreWithItems(id);
        return View(Item);
    }

    [HttpPost]
    public IActionResult Update(GetStoreViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }
        _storeService.UpdateStore(viewModel);
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Update(string Id)
    {
        var oldStore =await _storeService.GetStoreById(Id);
        return PartialView(oldStore);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(string id)
    {
        var store =await  _storeService.GetStoreById(id);
        return PartialView(store);
    }

    [HttpPost]
    public async Task<IActionResult>Delete(string id ,bool confirmDelete = true)
    {
        var store = await _storeService.DeleteStore(id);
        return RedirectToAction(nameof(Index));
    }



}

CodeZoneTest/Controllers/StoreItemsController.cs
using CodeZoneTest.Interfaces;
using CodeZoneTest.ViewModels.StoreItems;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace CodeZoneTest.Controllers
{
    public class StoreItemsController : Controller
    {
        private readonly IStoreItemsServices _storeItemsServices;
        private readonly IStoreServices _storeServices;
        private readonly IItemServices _itemServices;

        public StoreItemsController(IStoreItemsServices storeItemsServices , IStoreServices storeServices ,IItemServices itemServices)
        {
            _storeItemsServices = storeItemsServices;
            _storeServices = storeServices;
            _itemServices = itemServices;
        }
        public IActionResult Index(AssignItemToStoreViewModel viewModel)
        {
            var stores =  _storeServices.All();
            var items =  _itemServices.All();
            var model = new IndexItemsStoresViewModel
            {
                AllStore = stores,
                AllItems = items,
            };
            if(viewModel.StoreId.IsNullOrEmpty())
            {
                model.StoreId = viewModel.StoreId;
                model.ItemId = viewModel.ItemId;
                model.ItemQuantity = viewModel.ItemQuantity;
            }
            return View(model);
        }

        public int GetQuantity(string storeId , string itemId)
        {
            var itemQuantity = _storeItemsServices.GetItemsQuantity(storeId, itemId);
            return  itemQuantity ;
        }

        [HttpPost]
        public IActionResult Add(AssignItemToStoreViewModel model )
        {
            if(!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index), model);
            }
            var result =  _storeItemsServices.AssignItemToStoreAsync(model);
            return RedirectToAction(nameof(Details), "Store", routeValues: new { id = result.StoreId});
        }
    }
}

CodeZoneTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - CodeZoneTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/CodeZoneTest.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodeZoneTest</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Stores</a>
                        </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - CodeZoneTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CodeZoneTest/Views/Shared/_MyLayout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - MVC</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed bg-dark">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white shadow-lg">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link fw-bolder text-white fs-5 mx-2 px-5" asp-action="Index" asp-controller="Store">
                            <i class="fa-solid fa-shop fw-bolder text-white fs-5"></i>
                            Stores
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fw-bolder text-white fs-5 mx-2 px-5" asp-action="Index" asp-controller="Item">
                            <i class="fa-brands fa-product-hunt fw-bolder text-white fs-5"></i>
                            Items
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fw-bolder text-white fs-5 mx-2 px-5" asp-action="Index" asp-controller="StoreItems">
                            <i class="fa-solid fa-basket-shopping  fw-bolder text-white fs-5"></i>
                            Items Stores
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
   <main class="py-5 bg-dark" id="Custom-Main">
       <div class="container-fluid">
           @RenderBody()
       </div>
   </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>